In [1]:
#References:
# Week 6 and Week 7 slides and class notes and codes provide on blackboard
# https://medium.com/@rakendd/decision-tree-from-scratch-9e23bcfb4928

In [2]:
import pandas as pd

customerData=pd.read_csv("E:\Local Disk D\IIT-C\Sem 4\CS 584 Machine Learning\Homeworks\Homework 3\CustomerSurveyData.csv")

customerDataFrame=pd.DataFrame(customerData)

print(customerDataFrame.head())

        CustomerID  Region  TownSize  Gender  Age  EducationYears  \
0  0002-GTOKLU-YVY       5       4.0    Male   63              16   
1  0003-RLTRGE-IW2       1       1.0    Male   52              11   
2  0003-UTGKPR-PRU       2       2.0    Male   73              14   
3  0008-ZIQQOT-SGB       3       1.0  Female   40              21   
4  0012-CIVYLF-839       4       5.0    Male   40              12   

    JobCategory UnionMember  EmploymentLength Retired       ...        \
0         Sales          No                 3      No       ...         
1  Professional          No                14      No       ...         
2  Professional         Yes                11      No       ...         
3         Sales          No                 3      No       ...         
4         Labor          No                 9      No       ...         

  CallWait  CallForward  ThreeWayCalling  EBilling TVWatchingHours OwnsPC  \
0      Yes           No              Yes       Yes              18   

In [3]:
# customerDataFrame.head()

newcustomerData=customerDataFrame[['CreditCard','JobCategory','CarOwnership']]

print(newcustomerData.head(20))

          CreditCard   JobCategory CarOwnership
0   American Express         Sales          Own
1   American Express  Professional          Own
2               Visa  Professional        Lease
3   American Express         Sales          Own
4           Discover         Labor          Own
5   American Express        Crafts          Own
6         MasterCard  Professional         None
7               Visa  Professional          Own
8               Visa  Professional          Own
9               Visa  Professional          Own
10          Discover   Agriculture          Own
11        MasterCard         Sales          Own
12              Visa         Sales          Own
13          Discover        Crafts        Lease
14              Visa         Sales          Own
15  American Express         Sales          Own
16              Visa         Sales        Lease
17        MasterCard   Agriculture          Own
18        MasterCard   Agriculture          Own
19  American Express         Labor      

In [4]:
# totalLease=(customerDataFrame.CarOwnership=='Lease').count()

totalLease=(newcustomerData['CarOwnership']=='Lease').value_counts()

totalOwn=(newcustomerData['CarOwnership']=='Own').value_counts()

totalNone=(newcustomerData['CarOwnership']=='None').value_counts()

totalRows=len(customerDataFrame)

print(totalLease)

print(totalOwn)

print(totalNone)

print(totalRows)

False    4201
True      799
Name: CarOwnership, dtype: int64
True     3704
False    1296
Name: CarOwnership, dtype: int64
False    4503
True      497
Name: CarOwnership, dtype: int64
5000


In [5]:
values = newcustomerData.CarOwnership.unique()
for uniqueValue in values:
    print(newcustomerData.CarOwnership.value_counts()[uniqueValue]/len(newcustomerData.CarOwnership))

0.7408
0.1598
0.0994


In [6]:
# 
print("1(a)")

import numpy as np
# from numpy import log2 as log
nodeEntropy = 0  #Initialize Entropy
uniqueValues = newcustomerData.CarOwnership.unique()  #Unique objects - 'Lease', 'Own','None'

for uniqueValue in uniqueValues:
    pij = newcustomerData.CarOwnership.value_counts()[uniqueValue]/len(newcustomerData.CarOwnership) 
    nodeEntropy += -pij*np.log2(pij)
    
print(nodeEntropy)

1(a)
1.0744900777690842


In [7]:
# import math
# from scipy.stats import entropy

# # leaseAll=crossTable.iat["Lease","All"]
# print("1(a)")
# entropy=-(799/5000)*math.log2(799/5000)-(497/5000)*math.log2(497/5000)-3704/5000*math.log2(3704/5000)

# print(entropy)

# # print(leaseAll)

# print(entropy([799/5000, 497/5000, 3704/5000], base=2))

In [8]:
#possible binary-splits from the CreditCard predictor
print("1(b)")
givenValues=['American Express','Discover','MasterCard','Others','Visa']

totalDistict=len(givenValues)

print("Total number of disticnt value for nominal predictor: ",totalDistict)

totalBinarySplits=(2**(totalDistict-1))-1

print("Total number of binary splits: ",totalBinarySplits)

1(b)
Total number of disticnt value for nominal predictor:  5
Total number of binary splits:  15


In [139]:
# 
print("1(c)")
targetvariable=newcustomerData['CarOwnership']
nominalPredictor=newcustomerData['CreditCard']

crossTable=pd.crosstab(nominalPredictor,targetvariable, margins=True,dropna = True)

print(crossTable['Lease']['American Express'])

print(crossTable,"\n")

crossTablearray=(np.array(crossTable.iloc[0:5,:-1]))
print(crossTablearray)

1(c)
133
CarOwnership      Lease  None   Own   All
CreditCard                               
American Express    133   119   734   986
Discover            175   120  1049  1344
MasterCard          196   114   890  1200
Others               49    21   153   223
Visa                246   123   878  1247
All                 799   497  3704  5000 

[[ 133  119  734]
 [ 175  120 1049]
 [ 196  114  890]
 [  49   21  153]
 [ 246  123  878]]


In [10]:
# 
print("1(c)")

attributes=newcustomerData['CreditCard'].unique()

targetVariables=newcustomerData['CarOwnership'].unique()

# entropy=0

for attribute in attributes:
    entropyEachRow=0
    
    for targetVariable in targetVariables:
        
        p=crossTable[targetVariable][attribute]             #
        N=crossTable['All'][attribute]                      #
        Pij=p/N
        entropyEachRow+=-Pij*np.log2(Pij)
        
    print("Entropy of the ",attribute,":",entropyEachRow)
    
#     tableEntropy += rowEntropy *  crossTable.iloc[iRow,(nColumns-1)]
#     tableEntropy = tableEntropy /  crossTable.iloc[(nRows-1),(nColumns-1)]
#     return(tableEntropy)

# for attribute in attributes:
#     for targetVariable in targetVariables
    
# print(-(133/986)*np.log2(133/986)-(119/986)*np.log2(119/986)-734/986*np.log2(734/986))

1(c)
Entropy of the  American Express : 1.0750088593574028
Entropy of the  Visa : 1.1479670231237966
Entropy of the  Discover : 0.973200661032307
Entropy of the  MasterCard : 1.0693592329365411
Entropy of the  Others : 1.174264078521314


In [209]:
print("1(c)")
# print(crossTablearray)
tempCrossTable=crossTable

rows=tempCrossTable.shape[0]
columns=tempCrossTable.shape[1]

for i in range(rows-1):
    selected=np.array(tempCrossTable.iloc[i,:-1])
    
    droppedRow=tempCrossTable.drop(tempCrossTable.index[i])
       
#     rest=np.array((tempCrossTable.iloc[1:5,:-1]).sum(axis=0))
    rest=np.array((droppedRow.iloc[:-1,:-1]).sum(axis=0))
    
    print("Selected Rows: \n",selected)
#     print(droppedRow)
    print("Sum of rest of the rows: \n",rest,"\n")
#     newCrossTable=pd.crosstab(index=[selected,rest],
#                               columns=['Lease','None','Own'], margins=True,dropna = True)
    
    print(newCrossTable)

1(c)
Selected Rows: 
 [133 119 734]
Sum of rest of the rows: 
 [ 666  378 2970] 

col_0       Lease All
col_1        None    
col_2         Own    
row_0 row_1          
119   378       1   1
133   666       1   1
734   2970      1   1
All             3   3
Selected Rows: 
 [ 175  120 1049]
Sum of rest of the rows: 
 [ 624  377 2655] 

col_0       Lease All
col_1        None    
col_2         Own    
row_0 row_1          
120   377       1   1
175   624       1   1
1049  2655      1   1
All             3   3
Selected Rows: 
 [196 114 890]
Sum of rest of the rows: 
 [ 603  383 2814] 

col_0       Lease All
col_1        None    
col_2         Own    
row_0 row_1          
114   383       1   1
196   603       1   1
890   2814      1   1
All             3   3
Selected Rows: 
 [ 49  21 153]
Sum of rest of the rows: 
 [ 750  476 3551] 

col_0       Lease All
col_1        None    
col_2         Own    
row_0 row_1          
21    476       1   1
49    750       1   1
153   3551      1   1
Al

In [200]:
print("1(c)")
# print(crossTablearray)
tempCrossTable=crossTable

for i in range(rows-1):
    for j in range(1,rows-1):
        if(j>i):
            selected=np.array((tempCrossTable.iloc[i:j+1,:-1]).sum(axis=0)) 
            droppedRows=tempCrossTable.drop(tempCrossTable.index[[i,j]])       
            rest=np.array((droppedRows.iloc[:-1,:-1]).sum(axis=0))
        
            print("Selected Rows: \n",i,j,selected)
#           print("Dropped Rows: \n",droppedRows)
            print("Sum of rest of the rows: \n",i,j,rest)   

[[ 133  119  734]
 [ 175  120 1049]
 [ 196  114  890]
 [  49   21  153]
 [ 246  123  878]]
Selected Rows: 
 0 1 [ 308  239 1783]
Sum of rest of the rows: 
 0 1 [ 491  258 1921]
Selected Rows: 
 0 2 [ 504  353 2673]
Sum of rest of the rows: 
 0 2 [ 470  264 2080]
Selected Rows: 
 0 3 [ 553  374 2826]
Sum of rest of the rows: 
 0 3 [ 617  357 2817]
Selected Rows: 
 0 4 [ 799  497 3704]
Sum of rest of the rows: 
 0 4 [ 420  255 2092]
Selected Rows: 
 1 2 [ 371  234 1939]
Sum of rest of the rows: 
 1 2 [ 428  263 1765]
Selected Rows: 
 1 3 [ 420  255 2092]
Sum of rest of the rows: 
 1 3 [ 575  356 2502]
Selected Rows: 
 1 4 [ 666  378 2970]
Sum of rest of the rows: 
 1 4 [ 378  254 1777]
Selected Rows: 
 2 3 [ 245  135 1043]
Sum of rest of the rows: 
 2 3 [ 554  362 2661]
Selected Rows: 
 2 4 [ 491  258 1921]
Sum of rest of the rows: 
 2 4 [ 357  260 1936]
Selected Rows: 
 3 4 [ 295  144 1031]
Sum of rest of the rows: 
 3 4 [ 504  353 2673]


In [13]:
targetvariable=customerDataFrame['CarOwnership']
nominalPredictor=customerDataFrame['JobCategory']

crossTableJob=pd.crosstab(nominalPredictor,targetvariable, margins=True,dropna = True)

print(crossTableJob)

CarOwnership  Lease  None   Own   All
JobCategory                          
Agriculture      40    20   152   212
Crafts           74    59   319   452
Labor           105    58   523   686
Professional    187   151  1042  1380
Sales           306   148  1181  1635
Service          86    61   473   620
All             798   497  3690  4985


In [14]:
# 
print("2(a)")

import numpy as np

LikelihoodData=pd.read_csv("E:\Local Disk D\IIT-C\Sem 4\CS 584 Machine Learning\Homeworks\Homework 3\Purchase_Likelihood.csv")

LikelihoodDataFrame=pd.DataFrame(LikelihoodData)

targetVariable=LikelihoodDataFrame['A']

parameterValue=np.mean(targetVariable)

print(parameterValue)


print("There is only one parameter involved")
# print(LikelihoodDataFrame)

2(a)
0.9275459264125162
There is only one parameter involved


In [15]:
#Marginal Counts

print("2(b)")

uniqueValues=LikelihoodData.A.unique()
result=LikelihoodData.A.value_counts()[uniqueValues]

print(result)


2(b)
1    426067
0    143691
2     95491
Name: A, dtype: int64


In [131]:
#Maximum Likelihood

print("2(c)")

tototalCount_0=LikelihoodData.A.value_counts()[0]

tototalCount_1=LikelihoodData.A.value_counts()[1]

tototalCount_2=LikelihoodData.A.value_counts()[2]

totalCount=len(LikelihoodData.A)

prob_0=tototalCount_0/totalCount

prob_1=tototalCount_1/totalCount

prob_2=tototalCount_2/totalCount

print("Predicted Probability of Zero: ",prob_0)

print("Predicted Probability of One: ",prob_1)

print("Predicted Probability of two: ",prob_2)


logLikelihood=(tototalCount_0)*np.log(prob_0)+(tototalCount_1)*np.log(prob_1)+(tototalCount_2)*np.log(prob_2)


print("Log Likelihood: ",logLikelihood)

# l=logLikelihood*(-1)

# MLE_L=np.exp(l)


MLE_L=((prob_0)**(tototalCount_0))*((prob_1)**(tototalCount_1))*((prob_2)**(tototalCount_2))

print("Maximum Likelihood: ",MLE_L)

# print(totalCount)



2(c)
Predicted Probability of Zero:  0.21599581510081187
Predicted Probability of One:  0.64046244338586
Predicted Probability of two:  0.1435417415133281
Log Likelihood:  -595406.7618844224
Maximum Likelihood:  0.0


In [17]:
# Log  Likelihood
print("2(d)")


print("Log Likelihood: ",logLikelihood)


2(d)
Log Likelihood:  -595406.7618844224


In [18]:
# Likelihood estimate of intercepts
print("2(e)")

beta_10=np.log(prob_0/prob_0)

beta_20=np.log(prob_1/prob_0)

beta_30=np.log(prob_2/prob_0)


print("Likelihodd Estimate of intercept beata_10: ",beta_10)

print("Likelihodd Estimate of intercept beata_20: ",beta_20)

print("Likelihodd Estimate of intercept beata_30: ",beta_30)

2(e)
Likelihodd Estimate of intercept beata_10:  0.0
Likelihodd Estimate of intercept beata_20:  1.0869314502545038
Likelihodd Estimate of intercept beata_30:  -0.4086331584354002


In [36]:
#CrossTab with nominal predictors group_size

print("2(f)")

targetvariable=LikelihoodDataFrame['A']
nominalPredictor1=LikelihoodDataFrame['group_size']
nominalPredictor2=LikelihoodDataFrame['homeowner']
nominalPredictor3=LikelihoodDataFrame['married_couple']

contigencyTable=pd.crosstab(index=[nominalPredictor1,nominalPredictor2,nominalPredictor3],
                              columns=LikelihoodDataFrame["A"],margins=True,dropna = True)

x = contigencyTable.drop('All', 1)

percentTable = contigencyTable.div(x.sum(1), axis='index')*100

print("Frequency Table: \n")
print(contigencyTable)
print( )
print("Percent Table: \n")
print(percentTable)

2(f)
Frequency Table: 

A                                         0       1      2     All
group_size homeowner married_couple                               
1          0         0                67309  154434  39363  261106
                     1                 2554    4108   1284    7946
           1         0                42973  163625  31820  238418
                     1                 2624    7385   1826   11835
2          0         0                 2564    5227   1611    9402
                     1                 5835   18336   4222   28393
           1         0                 4066    9548   2437   16051
                     1                13263   57954  11330   82547
3          0         0                   70     170     14     254
                     1                  305     779    225    1309
           1         0                  111     254     62     427
                     1                 1796    3866   1204    6866
4          0         0                

In [20]:
#CrossTab with nominal predictors group_size
print("2(f)")

targetvariable=LikelihoodDataFrame['A']
nominalPredictor=LikelihoodDataFrame['group_size']

contig_group_size=pd.crosstab(nominalPredictor,targetvariable, margins=True,dropna = True)

x1 = contig_group_size.drop('All', 1)

percentTable = contig_group_size.div(x1.sum(1), axis='index')*100

print("Frequency Table for Group size: \n")
print(contig_group_size)
print( )
print("Percent Table for Group size: \n")
print(percentTable)

2(f)
Frequency Table for Group size: 

A                0       1      2     All
group_size                               
1           115460  329552  74293  519305
2            25728   91065  19600  136393
3             2282    5069   1505    8856
4              221     381     93     695
All         143691  426067  95491  665249

Percent Table for Group size: 

A                   0          1          2    All
group_size                                        
1           22.233562  63.460202  14.306236  100.0
2           18.863138  66.766623  14.370239  100.0
3           25.767841  57.238031  16.994128  100.0
4           31.798561  54.820144  13.381295  100.0
All         21.599582  64.046244  14.354174  100.0


In [21]:
#CrossTab with nominal predictors homeowner
print("2(f)")

targetvariable=LikelihoodDataFrame['A']
nominalPredictor=LikelihoodDataFrame['homeowner']

contig_homeowner=pd.crosstab(nominalPredictor,targetvariable, margins=True,dropna = True)

x2 = contig_homeowner.drop('All', 1)

percentTable3 = contig_homeowner.div(x2.sum(1), axis='index')*100

print("Frequency Table for homeowner: \n")
print(contig_homeowner)
print( )
print("Percent Table for homeowner: \n")
print(percentTable3)

2(f)
Frequency Table for homeowner: 

A               0       1      2     All
homeowner                               
0           78659  183130  46734  308523
1           65032  242937  48757  356726
All        143691  426067  95491  665249

Percent Table for homeowner: 

A                  0          1          2    All
homeowner                                        
0          25.495344  59.357001  15.147655  100.0
1          18.230238  68.101848  13.667913  100.0
All        21.599582  64.046244  14.354174  100.0


In [22]:
#CrossTab with nominal predictors married_couple
print("2(f)")

targetvariable=LikelihoodDataFrame['A']
nominalPredictor=LikelihoodDataFrame['married_couple']

contig_married_couple=pd.crosstab(nominalPredictor,targetvariable, margins=True,dropna = True)

x3 = contig_married_couple.drop('All', 1)

percentTable3 = contig_married_couple.div(x3.sum(1), axis='index')*100

print("Frequency Table for married couple: \n")
print(contig_married_couple)
print( )
print("Percent Table for married couple: \n")
print(percentTable3)

2(f)
Frequency Table for married couple: 

A                    0       1      2     All
married_couple                               
0               117110  333272  75310  525692
1                26581   92795  20181  139557
All             143691  426067  95491  665249

Percent Table for married couple: 

A                       0          1          2    All
married_couple                                        
0               22.277303  63.396818  14.325879  100.0
1               19.046698  66.492544  14.460758  100.0
All             21.599582  64.046244  14.354174  100.0


In [23]:
# 
print("2(g)")

print("Based on the contingency table in (f), we  expect the Quasi-complete separation ")

2(g)
Based on the contingency table in (f), we  expect the Quasi-complete separation 


In [30]:
# 
print("2(h)")

import sklearn.metrics as metrics
import statsmodels.api as stats


targetVariable_A = LikelihoodDataFrame['A'].astype('category')
y = targetVariable_A
y_category = y.cat.categories

print(y_category,"\n")

groupSize = LikelihoodDataFrame['group_size']
X = pd.get_dummies(groupSize)
X = X.join(LikelihoodDataFrame[[ 'homeowner','married_couple']])
X = stats.add_constant(X, prepend=True)

print(X.head(20))

2(h)
Int64Index([0, 1, 2], dtype='int64') 

    const  1  2  3  4  homeowner  married_couple
0     1.0  0  1  0  0          0               1
1     1.0  0  1  0  0          0               1
2     1.0  0  1  0  0          0               1
3     1.0  0  1  0  0          0               1
4     1.0  0  1  0  0          0               1
5     1.0  0  1  0  0          0               1
6     1.0  0  1  0  0          0               1
7     1.0  0  1  0  0          0               1
8     1.0  0  1  0  0          0               1
9     1.0  1  0  0  0          0               0
10    1.0  1  0  0  0          0               0
11    1.0  1  0  0  0          0               0
12    1.0  1  0  0  0          0               0
13    1.0  1  0  0  0          0               0
14    1.0  1  0  0  0          0               0
15    1.0  1  0  0  0          0               0
16    1.0  1  0  0  0          0               0
17    1.0  1  0  0  0          0               0
18    1.0  1  0  0  0    

In [33]:
# 
print("2(h)")

logit = stats.MNLogit(y, X)

print("Name of Target Variable:", logit.endog_names)

print("Name(s) of Predictors:", logit.exog_names)

fitModel = logit.fit(method='newton', full_output = True, maxiter = 100, tol = 1e-8)
modelParameter = fitModel.params

print("Model Parameter Estimates:\n", modelParameter)

print("Model Log-Likelihood Value:\n", logit.loglike(modelParameter.values))

2(h)
Name of Target Variable: A
Name(s) of Predictors: ['const', 1, 2, 3, 4, 'homeowner', 'married_couple']
Optimization terminated successfully.
         Current function value: 0.889797
         Iterations 8
Model Parameter Estimates:
                        0         1
const           0.408313 -0.564586
1               0.424290  0.028582
2               0.437360  0.074773
3              -0.094090 -0.105714
4              -0.359274 -0.562208
homeowner       0.462188  0.214712
married_couple  0.116990  0.090834
Model Log-Likelihood Value:
 -591936.7938327907


In [35]:
# 
print("2(h)")
y_predProb = fitModel.predict(X)
y_predict = pd.to_numeric(y_predProb.idxmax(axis=1))

y_predictClass = y_category[y_predict]

y_confusion = metrics.confusion_matrix(y, y_predictClass)
print("Confusion Matrix (Row is True, Column is Predicted) = \n")
print(y_confusion)

y_accuracy = metrics.accuracy_score(y, y_predictClass)
print("Accuracy Score = ", y_accuracy)

2(h)
Confusion Matrix (Row is True, Column is Predicted) = 

[[     0 143691      0]
 [     0 426067      0]
 [     0  95491      0]]
Accuracy Score =  0.64046244338586


In [55]:
# 
print("2(i)")

targetvariable=LikelihoodDataFrame['A']
nominalPredictor1=LikelihoodDataFrame['group_size']
nominalPredictor2=LikelihoodDataFrame['homeowner']
nominalPredictor3=LikelihoodDataFrame['married_couple']

contigencytable=pd.crosstab(index=[nominalPredictor1,nominalPredictor2,nominalPredictor3],
                              columns=LikelihoodDataFrame["A"],margins=True,dropna = True)

total = contigencytable.drop('All', 1)

predictedProbTable = contigencytable.div(total.sum(1), axis='index')

print("Predicted Probability table: \n\n",predictedProbTable)

2(i)
Predicted Probability table: 

 A                                           0         1         2  All
group_size homeowner married_couple                                   
1          0         0               0.257784  0.591461  0.150755  1.0
                     1               0.321420  0.516990  0.161591  1.0
           1         0               0.180242  0.686295  0.133463  1.0
                     1               0.221715  0.623997  0.154288  1.0
2          0         0               0.272708  0.555946  0.171347  1.0
                     1               0.205508  0.645793  0.148699  1.0
           1         0               0.253318  0.594854  0.151829  1.0
                     1               0.160672  0.702073  0.137255  1.0
3          0         0               0.275591  0.669291  0.055118  1.0
                     1               0.233002  0.595111  0.171887  1.0
           1         0               0.259953  0.594848  0.145199  1.0
                     1               0.2

In [79]:
# the maximum odd Prob(A = 1)/Prob(A = 0) value
print("2(i)")

prdictedProb_0=predictedProbTable[0][2][1][1]

prdictedProb_1=predictedProbTable[1][2][1][1]

maxOdd=prdictedProb_1/prdictedProb_0

print("Predicted probability of 0: \n",prdictedProb_0)

print("Predicted probability of 1: \n",prdictedProb_1)

print("Maximum odd Probability prdictedProb_1/prdictedProb_0: \n ",maxOdd)

2(i)
Predicted probability of 0: 
 0.1606721019540383
Predicted probability of 1: 
 0.7020727585496748
Maximum odd Probability prdictedProb_1/prdictedProb_0: 
  4.36959963809093


In [ ]:
# The odds ratio for group_size = 3 versus group_size = 1, and A = 2 versus A = 0,acccording to the multinomial logistic model

print("2(j)")

prdictedProb_0=predictedProbTable[0][3][2][2]

prdictedProb_1=predictedProbTable[1][2][1][1]
